import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "./components/header";
import { UserProvider } from "./contexts/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <Header />
          {children}

          <footer className="bg-white border-t border-gray-200 py-6 mt-6">
            <div className="max-w-6xl mx-auto px-4 flex justify-between items-center text-sm text-gray-500">
              <span>© 2025 GameBench. All rights reserved.</span>
              <div className="space-x-4">
                <Link href="#" className="hover:underline">
                  Privacy
                </Link>
                <Link href="#" className="hover:underline">
                  Terms
                </Link>
                <Link href="#" className="hover:underline">
                  Contact
                </Link>
                <Link href="/login" className="hover:underline">
                  Login
                </Link>
              </div>
            </div>
          </footer>
        </UserProvider>
      </body>
    </html>
  );
}
